from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from ..schemas.course import CourseOutput
from io import BytesIO

def generate_course_pdf(course: CourseOutput) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=50, leftMargin=50,
        topMargin=50, bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    brand_color = colors.HexColor("#6366f1")
    text_main = colors.HexColor("#1e293b")
    text_muted = colors.HexColor("#64748b")
    
    title_style = ParagraphStyle(
        'BrandTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        textColor=brand_color,
        spaceAfter=20,
        alignment=1 # Center
    )
    
    header_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=16,
        textColor=text_main,
        spaceBefore=15,
        spaceAfter=10,
        borderPadding=5,
        borderWidth=0,
        borderColor=brand_color,
        backColor=colors.HexColor("#f8fafc")
    )
    
    normal_style = ParagraphStyle(
        'NormalBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        textColor=text_main,
        leading=14
    )
    
    label_style = ParagraphStyle(
        'Label',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        textColor=brand_color,
        textTransform='uppercase'
    )

    flowables = []
    
    # --- Header / Brand ---
    flowables.append(Paragraph("Pathweaver AI", title_style))
    flowables.append(Paragraph(course.course_title, styles['Heading2']))
    flowables.append(Spacer(1, 12))
    
    # --- Overview Section ---
    flowables.append(Paragraph("ROADMAP OVERVIEW", label_style))
    flowables.append(Paragraph(course.overview, normal_style))
    flowables.append(Spacer(1, 10))
    flowables.append(Paragraph(f"<b>Estimated Duration:</b> {course.estimated_duration}", normal_style))
    flowables.append(Spacer(1, 30))
    
    # --- Modules ---
    for mod in course.modules:
        # Module Header Card (Table for background)
        mod_title = f"Module {mod.module_number}: {mod.title}"
        
        data = [[Paragraph(mod_title, ParagraphStyle('ModHeader', parent=styles['Heading3'], textColor=colors.white))]]
        t = Table(data, colWidths=[letter[0] - 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), brand_color),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
        ]))
        flowables.append(t)
        flowables.append(Spacer(1, 12))
        
        # Details
        flowables.append(Paragraph(f"<b>Duration:</b> {mod.duration}", normal_style))
        flowables.append(Spacer(1, 8))
        
        # Objectives & Topics
        flowables.append(Paragraph("OBJECTIVES", label_style))
        obj_list = "".join([f"• {o}<br/>" for o in mod.objectives])
        flowables.append(Paragraph(obj_list, normal_style))
        flowables.append(Spacer(1, 10))
        
        flowables.append(Paragraph("KEY TOPICS", label_style))
        top_list = ", ".join(mod.topics)
        flowables.append(Paragraph(top_list, normal_style))
        flowables.append(Spacer(1, 10))
        
        if mod.mini_project:
            flowables.append(Paragraph("PRACTICAL PROJECT", label_style))
            flowables.append(Paragraph(mod.mini_project, normal_style))
            flowables.append(Spacer(1, 10))
            
        flowables.append(Paragraph("RESOURCES", label_style))
        res_list = ", ".join(mod.resources)
        flowables.append(Paragraph(res_list, normal_style))
        
        flowables.append(Spacer(1, 24))
        
    # --- Footer ---
    def add_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.setStrokeColor(text_muted)
        canvas.line(50, 40, letter[0]-50, 40)
        canvas.drawString(50, 25, "Generated by Pathweaver AI - Your Personalized Learning Guide")
        canvas.drawRightString(letter[0]-50, 25, "Page %d" % doc.page)
        canvas.restoreState()

    doc.build(flowables, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer
